/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lang_ada_ImportAst */

#ifndef _Included_lang_ada_ImportAst
#define _Included_lang_ada_ImportAst
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lang_ada_ImportAst
 * Method:    _importAdaAst
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lang_ada_ImportAst__1importAdaAst
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
